config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "/apropos", to: "pages#apropos"
  get "calendly_privee", to: "pages#calendly_privee"
  get "condition", to: "pages#condition"
  get "/entreprise", to: "pages#entreprise"
  get "/faq", to: "pages#faq"
  get "/formation", to: "pages#formation"
  get "/merci", to: "pages#merci"
  get "/mentions", to: "pages#mentions"
  get "/private", to: "pages#private"
  get "/tarifs", to: "pages#tarifs"
  get "/thanks", to: "contacts#thanks"
  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :email,     validate: /\A([\w.%+\-]+)@([\w\-]+\.)+(\w{2,})\z/i
  attribute :first_name,      validate: true
  attribute :last_name,      validate: true
  attribute :company
  attribute :phone
  attribute :job
  attribute :message

  def headers
    {
      subject: "Contact Form, #{first_name} #{last_name} #{email}",
      to: "contact@beyondboxing.fr",
      from: "contact@beyondboxing.fr"
    }
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params) 
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
    redirect_to thanks_path
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :message, :company, :job, :phone)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def apropos
  end

  def entreprise
  end

  def faq
  end

  def formation
  end

  def home
  end

  def merci
  end

  def private
  end

  def tarifs
  end

  def condition
  end

  def calendly_privee
  end

  def mentions
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/create.html.erb
<h1>page, remerciements</h1>

app/views/contacts/thanks.html.erb
<section class="contact_thank">
	<div class="container">
		<div class="row">
			<div class="col-md-6 offset-md-3">
				<h1 class="text-center">
					Merci pour votre message<br>
				</h1>
				<div class="text-center">
					<img src="sent.png" class="img-fluid">
					<h5>Nous allons vous répondre dans les plus brefs délais</h5>
				</div>
				<div class="text-center">
					<a class="btn btn-warning" href="https://www.beyondboxing.fr/" type="button">Retour à la page d'accueil</a>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/layouts/_footer.html.erb
<footer class="text-center text-lg-start bg-white text-muted">
  <!-- Section: Links  -->
  <section class="">
    <hr>
    <div class="container text-center text-md-start mt-5">
      <h1 class="footer text-center mt-5">PRETS POUR L'EXPERIENCE ?</h1>
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-lg-4 col-md-4 col-sm-12 mb-4">
          <div class="text-center">
          <h6 class="text-uppercase fw-bold mb-4">
            A propos
          </h6>
          <p>
            <%=  link_to "A propos",apropos_path, class: "nav-link"%>
          </p>
          <p>
            <%= link_to "Contact", new_contact_path, class: "nav-link" %>
          </p>
          <p>
            <%= link_to "FAQ", faq_path, class: "nav-link" %>
          </p>
          </div>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <!-- <div class="col-md-6 col-lg-6 col-sm-12 mb-4">
          <!-- Links
          <button type="button" class="btn btn-outline-secondary btn-lg mb-3"><a href="https://www.beyondboxing.fr/private">Réserver un cours privé</a></button>
          <button type="button" class="btn btn-outline-secondary btn-lg mb-3"><a href="https://www.beyondboxing.fr/contacts/new">Contacter notre équipe</a></button>

        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-lg-4 col-md-4 col-sm-12">
          <!-- Links -->
          <div class="text-center">
          <h6 class="text-uppercase fw-bold mb-4">Services</h6>
          <p>
            <%= link_to "Pour les particuliers", private_path, class: "nav-link" %>
          </p>
          <p>
            <%= link_to "Pour les entreprises", entreprise_path, class: "nav-link" %>
          </p>
          <p>
            <%= link_to "CGV", condition_path, class: "nav-link" %>
          </p>
          <p>
            <%= link_to "Mentions légales", mentions_path, class: "nav-link" %>
          </p>
          </div>
        </div>

        <div class="col-lg-4 col-md-4">
          <div class="text-center">
            <h6 class="text-uppercase fw-bold mb-4">Les Réseaux sociaux</h6>
            <!--<a href="" class="me-2 link-secondary">
              <%#= image_tag "img/linkedin.png", class:"icon"%>
            </a>
            <a href="" class="me-2 link-secondary">
              <%#= image_tag "img/facebook.png", class:"icon"%>
            </a>-->
            <a href="https://www.instagram.com/beyondboxingbymad/" class="me-2 link-secondary">
              <%= image_tag "img/instagram-color.png", class:"icon"%>
            </a>
            <a href="https://www.youtube.com/@beyondboxingchannel" class="me-2 link-secondary" target="blank">
              <%= image_tag "img/youtube-color.png" , class:"icon"%>
            </a>
            <a href="https://www.beyondboxing.fr/contacts/new" class="me-2 link-secondary">
              <%= image_tag "img/mail.png" , class:"icon"%>
            </a>
          </div>
        </div>
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center pb-5">
    <!-- <div class="container">
      <a href="" class="me-2 link-secondary">
        <%#= image_tag "img/linkedin.png", class:"icon"%>
      </a>
      <a href="" class="me-2 link-secondary">
        <%#= image_tag "img/facebook.png", class:"icon"%>
      </a>
      <a href="" class="me-2 link-secondary">
        <%#= image_tag "img/new-instagram.png", class:"icon"%>
      </a>
      <a href="https://www.youtube.com/@beyongboxingchannel" class="me-2 link-secondary">
        <%#= image_tag "img/youtube.png" , class:"icon"%>
      </a>
      <a href="https://www.beyondboxing.fr/contacts/new" class="me-2 link-secondary">
        <%#= image_tag "img/email-bg.png" , class:"icon"%>
      </a>
     </div>-->
    <h6 class="droits">

        ©2023 Beyond Boxing Tous droits réservés
        <!-- <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a> -->
    </h6>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <%= link_to root_path,class: "navbar-brand" do %>
     <span class="name">Beyond Boxing <b class="by">BY MAD</b></span>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
           <%= link_to "A propos", apropos_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Cours privé", private_path, class: "nav-link"%>
          </li>
          <li  class="nav-item active">
            <%= link_to "Entreprise", entreprise_path, class: "nav-link"%>
          </li>
          <li class="nav-item active">
           <%= link_to "Tarifs", tarifs_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
           <%= link_to "Merci", merci_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <a href=" https://www.youtube.com/@beyondboxingchannel"
              target="blank">
              <%= image_tag "img/yt_logo_rgb_light.png", class:"logo-youtube"%>
            </a>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google tag (gtag.js)-->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-LRPYPX7DF6%22%3E">
      </script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag (){dataLayer.push (arguments) ;}
        gtag ('js', new Date());
        gtag('config', 'G-LRPYPX7DF6');
      </script>
    <title>Beyond Boxing</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="Beyond Boxing | boxe, fitness et bonne humeur" />
    <meta name="keywords" content="Coaching, excellence, boxe française, hauts de seine, bienveillance, premium, respect, bonne humeur, femmes, parité, self-defense, tous publics" />
    <meta name="language" content="fr-FR" />
    <meta name="robots" content="all" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
        <script type="module" src="https://cookieconsent.popupsmart.com/js/CookieConsent.js" ></script>
      <script type="text/javascript" src="https://cookieconsent.popupsmart.com/js/App.js"></script>
      <script>
          popupsmartCookieConsentPopup({
              "siteName" : "beyondboxing" ,
              "notice_banner_type": "popup",
              "consent_type": "gdpr",
              "palette": "dark",
              "language": "French",
              "privacy_policy_url" : "https://www.beyondboxing.fr/mentions" ,
              "preferencesId" : "#open_prefrences_center" ,

          });
      </script>

      <noscript>Cookie Consent by <a href="https://popupsmart.com/" rel="nofollow noopener">Popupsmart Website</a></noscript>
  </body>
</html>

app/views/pages/calendly_privee.html.erb
<div class="container text-center" style="margin-top: 100px;">
	<h2 class="title_pricing">RESERVEZ VOTRE COURS</h2>
</div>
<section class="calendly" style="background-color:#d9d9d9;">
	<div class="container">
			<!-- Début de widget en ligne Calendly -->
			<div class="calendly-inline-widget"
				data-url="https://calendly.com/madboxing/coaching-prive"
				style="min-width:320px;height:630px;">
			</div>
			<!-- Fin de widget en ligne Calendly -->
	</div>
</section>
<script type="text/javascript"
  src="https://assets.calendly.com/assets/external/widget.js" async>
</script>

app/views/pages/condition.html.erb
<article>
  <div class="container-720 text-center">
    <h1 class="title_pricing">CONDITIONS DE VENTES</h1>
  </div>
</article>

<section class="conditions">
  <div class="container">
    <h5 >BEYOND BOXING</h5>
    <h6>
      Mademba EIRL - SIREN : 803639459
    </h6>
    <h6>
      Siège social : 37, rue Veuve Lacroix - 92250 La Garenne-Colombes
    </h6>
    <h4 class="sub_title">
      ARTICLE 1 -Domaine d'application
    </h4>
    <p>
    Les conditions générales de ventes décrites ci-après détaillent les droits et obligations de Mademba EIRL  <b>(« Beyond Boxing »)</b> et de toute personne physique ou morale qui achète l’une des prestations de service décrites ci-après en échange d’un paiement, <b>(le « Client »)</b> et régissent la vente de services listés à l’article 5 sur le site <a href="https://www.beyondboxing.fr/" >www.beyondboxing.fr</a> à compter de la validation de la commande par le client jusqu’à la réalisation de la prestation.
    </p>

    <h4 class="sub_title">
      ARTICLE 2 - Acceptation et champ d’application
    </h4>
    <p>
    Toute acceptation des devis, bons de commande de prestations en ce compris la clause « Je reconnais avoir pris connaissance et j’accepte les conditions générales de vente ci-annexées » implique l’acceptation sans réserve par le Client et son adhésion pleine et entière aux présentes conditions générales de vente qui prévalent sur tout autre document du Client, sauf négociation de conditions particulières entre les parties.
    </p>

    <h4 class="sub_title">
      ARTICLE 3 - Dispositions contractuelles
    </h4>
    <p>
    La nullité d’une clause contractuelle n’entraîne pas la nullité des conditions générales de vente de services sauf s’il s’agit d’une clause impulsive et déterminante ayant amené l’une des parties à conclure le contrat de prestation de services.
    </p>

    <h4 class="sub_title">
      ARTICLE 4 - Modification des conditions générales
    </h4>
    <p>
    Beyond Boxing se réserve la faculté de modifier ses conditions générales de ventes à tout moment.
    La version applicable sera donc celle en vigueur sur le site à la date de passation de la commande.
    </p>

    <h4 class="sub_title">
      ARTICLE 5 - Objet - Traitement
    </h4>
    <p>
    Les présentes conditions générales de vente établissent les conditions contractuelles exclusivement applicables aux prestations de services dont la liste suit : <br>
    - cours de boxe française sur mesure d'une heure ; <br>
    - initiation ou perfectionnement de boxe française ; et <br>
    - ateliers sport santé cours collectifs.
    </p>

    <h4 class="sub_title">
      ARTICLE 6 – Réservation des cours
    </h4>
    <p>
    La réservation des cours privés se fait en ligne sur le <a href="https://www.beyondboxing.fr/" >www.beyondboxing.fr</a><br>
    - choix par le Client d’une séance à l’unité, ou toute autre formule proposée par le Beyond Boxing en cliquant sur le bouton « réserver un cours » ; <br>
    - redirection vers un agenda en ligne (calendly) pour choisir le créneau horaire convenant. <br>
    La réservation n’est prise en compte qu’une fois le règlement reçu par Beyond Boxing.<br>
    Le Client doit être majeur pour réserver un cours à l’unité ou souscrire une formule.
    </p>

    <h4 class="sub_title">
      ARTICLE 7 - Tarifs
    </h4>
    <h6>7.1 Prix</h6>
    <p>
    Les prix s’entendent toutes taxes comprises sur la base des tarifs en vigueur qui figurent en annexe aux présentes pour les cours privés.<br>
    Pour les personnes morales, les prix s’entendent hors taxes.<br>
    out impôt, taxe, droit ou autre prestation à payer en application de la législation française et toute modification de ceux-ci sont à la charge du Client.<br>
    Si les prestations concernées ne sont pas mentionnées dans la grille tarifaire alors Beyond Boxing communiquera au Client le prix applicable en réponse au bon de commande.
    </p> <br><br>

    <h6>7.2 Modification du prix</h6>
    <p>
    Beyond Boxing se réserve le droit de modifier unilatéralement les prix des services à tout moment, notamment en cas d’augmentation des coûts, étant entendu que, en cas d’augmentation des prix postérieure à la commande, seul le prix fixé au jour de cette commande sera applicable au Client.
    </p>

    <h4 class="sub_title">
      ARTICLE 8 - Facturation
    </h4>
    <p>
    La facture reprend les informations ci-dessous : <br>
    - 	prestation concernée ou référence de la prestation ; et <br>
    - 	prix unitaire de la prestation.<br>
    La facture sera adressée directement au Client par Beyond Boxing.<br>
    La facture sera transmise à l’adresse mail communiquée par le Client.
    </p>

    <h4 class="sub_title">
      ARTICLE 9 – Modalités de paiement
    </h4>
    <p>
    Le règlement s’effectue : <br>
    - soit par virement bancaire ; <br>
    - soit par chèque ; ou <br>
    - soit en ligne via l’application. <br>
    Pour les personnes morales, les règlements seront effectués sous 30 jours suivant la date de la facturation.
    </p>

    <h4 class="sub_title">
      ARTICLE 10 – Référence commerciale
    </h4>
    <p>
    Sauf indication expresse contraire, le Client autorise Beyond Boxing par la commande de prestations auprès de Beyond Boxing à la publication de visuels (photos, vidéos, d’avatar) ou autres témoignages pouvant le représenter à des fins publicitaires et commerciales. <br> <br>
    Selon les articles 226-1 à 226-8 du code civil, tout individu jouit d’un droit au respect de sa vie privée ainsi que d’un droit à l’image.<br>
    En vertu de ces dispositions, la publication ou la reproduction d’une photographie ou d’une autre information sur laquelle une personne est clairement reconnaissable est possible avec son consentement préalable.<br>
    Font exception à cette règle les photos de foule où la personne n’est pas le sujet central ou bien les photos prises de loin ou de dos.
    <br>
    Le Client peut s’opposer à l’utilisation ultérieure desdits visuels et informations en l’indiquant par écrit à <%= link_to "contact@beyondboxing.com.", new_contact_path %><br>
    </p>

    <h4 class="sub_title">
      ARTICLE 11 – Informatiques et libertés
    </h4>
    <p>
    En application de la loi N°78-017 du 6 Janvier 1978 relative à l’informatique, aux fichiers et aux libertés, le Client est informé que ses réponses au formulaire d’inscription sont nécessaires au traitement et à l’activation de sa réservation auprès de Beyond Boxing.<br>
    Le Client est informé qu’il dispose d’un droit d’accès, d’opposition et de rectification sur les renseignements le concernant, détenus par Beyond Boxing et qui font l’objet d’un traitement informatique.
    <br>
    Ce droit d’accès et de rectification peut être exercé par courrier à l’adresse suivante :  37, rue Veuve Lacroix  - 92250 La Garenne-Colombes.<br>
    Les données concernant le Client sont destinées à la gestion de la prestation du Client par Beyond Boxing.
    <br>
    Pour les personnes morales, les règlements seront effectués sous 30 jours suivant la date de la facturation. <br>
    Le Client consent à ce que Beyond Boxing lui adresse par e-mail, sms ou téléphone, des offres et actualités sur ses services. Le Client peut s’y opposer en adressant un e-mail en ce sens à <%= link_to "contact@beyondboxing.com.", new_contact_path %><br>
    Le Client dispose d’un droit d’accès, de rectification et de suppression relativement aux informations le concernant qu’il peut exercer à tout moment en s’adressant à Beyond Boxing.
    </p>

    <h4 class="sub_title">
      ARTICLE 12 – Règlement des litiges
    </h4>
    <p>
    La présente convention est régie par le droit français.<br><br>
    A défaut de résolution amiable, tout différend entre le Client et Beyond Boxing relatif à l’existence, la validité, l’interprétation, l’exécution et la réalisation de la présente convention (ou de l’une quelconque de ces clauses) sera de la compétence exclusive des juridictions de l’ordre judiciaire de Nanterre.<br><br>

    Fait à La Garenne-Colombes, le 28 avril 2023
    </p>

  </div>
  </section>

app/views/pages/home.html.erb
<div class="section_home">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-12 col-sm-12 order-md-1 order-sm-1 mb-5 ">
        <h1 class="title_homepage">Quand boxe française, fitness et bonne humeur s'entremêlent</h1>
        <p class="baseline">
          "Plus qu'un sport, un état d'esprit,<br> Plus qu'un cours, une bouffée d'énergie"
        </p>
        <%= link_to "Réserver un cours", private_path, class: "btn btn-home", target:"blank"%>
      </div>

      <div class="col-lg-6 col-md-12 col-sm-12 order-md-2 order-sm-2">
        <iframe width="100%" height="300px" src="https://www.youtube.com/embed/4FQUP36-d6w?si=YdLhejYv5qPkW8LG" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>
        </iframe>
      </div>
    </div>
  </div>
</div>
 <section slide>
   <div class="container">
    <div class="slider">
      <div class="slide-track">
        <div class="slide">
          <img src= "fityou-color.PNG"class= "img-fluid fityou">
        </div>
        <div class="slide">
        <img src="CNOSF.svg.png" class="img-fluid cnosf">
        </div>
        <div class="slide">
          <img src="ASC-BNP.png" class="img-fluid asc">
        </div>
        <div class="slide">
        <img src="logo-paris.png" class="img-fluid">
        </div>
        <div class="slide">
        <img src="csme.jpg" class="img-fluid csme">
        </div>
        <div class="slide">
        <img src="cergybf.png" class="img-fluid cergy">
        </div>
        <div class="slide">
        <img src="aljt-logo.png" class="img-fluid aljt">
        </div>
        <div class="slide">
          <img src="jch.png" class="img-fluid jch">
        </div>
        <div class="slide">
          <img src="b9.jpg" class="img-fluid b9">
        </div>
        <div class="slide">
        <img src="kabubu.png" class="img-fluid kabubu">
        </div>
        <div class="slide" style="margin-right: 60px !important;">
        <img src="colosport-logo.png" class="img-fluid colo">
        </div>
        <div class="slide">
          <img src= "fityou-color.PNG"class= "img-fluid fityou">
        </div>
        <div class="slide">
        <img src="CNOSF.svg.png" class="img-fluid cnosf">
        </div>
        <div class="slide">
          <img src="ASC-BNP.png" class="img-fluid asc">
        </div>
      </div>
    </div>
  </div>
</section>
<!-- <div class="section_sponsor">
  <div class="container">
    <div class="row">
      <div class="col-lg-1 col-md-3 col-sm-12  col-xs-8.offset-xs-2 text-center mb-5">
        <img src="ASC-BNP.png" class="img-fluid">
      </div>

      <div class="col-lg-2 col-md-3 col-sm-12  col-xs-8.offset-xs-2 text-center mb-5">
        <img src="b9.jpg" class="img-fluid">
      </div>

      <div class="col-lg-1 col-md-3 col-sm-12 col-xs-8.offset-xs-2 text-center mb-5">
        <img src="csme.jpg" class="img-fluid">
      </div>

      <div class="col-lg-2 col-md-3 col-sm-12 col-xs-8.offset-xs-2 text-center mb-5">
        <img src="kabubu.png" class="img-fluid">
      </div>

      <div class="col-lg-2 col-md-3 col-sm-12  col-xs-8.offset-xs-2 text-center mb-5">
        <img src="colosport-logo.png" class="img-fluid">
      </div>

      <div class="col-lg-2 col-md-3 col-sm-12  col-xs-8.offset-xs-2 text-center mb-5">
        <img src="CNOSF.svg.png" class="img-fluid">
      </div>

      <div class="col-lg-1 col-md-3 col-sm-12  col-xs-8.offset-xs-2 text-center mb-5">
        <img src="logo-paris.png" class="img-fluid">
      </div>

      <div class="col-lg-1 col-md-3 col-sm-12  col-xs-8.offset-xs-2 text-center mb-5">
        <img src="aljt-logo.png" class="img-fluid">
      </div>
    </div>
  </div>
</div> -->

<div class="aside-home">
  <hr>
  <div class="container">
    <div class="row">
      <h1 class="text-center mt-5 mb-5">CHOISISSEZ L'OFFRE QUI VOUS CONVIENT</h1>
      <div class="col-lg-4 offset-lg-2 col-md-6">
        <div class="card home">
          <div class="card-body">
            <h5 class="card-title text-center">PARTICULIERS</h5>
            <h5 class="aside-home text-center">Coachings privés</h5>
            <h5 class="aside-home text-center">Cours collectifs</h5>
            <div class="text-center">
              <%= link_to "En savoir plus", private_path, class: "btn btn-hp hp-btn"%>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-6">
        <div class="card home">
          <div class="card-body">
            <h5 class="card-title text-center">ENTREPRISES</h5>
            <h5 class="aside-home text-center">Ateliers sport santé</h5>
            <h5 class="aside-home text-center">Cours collectifs</h5>
            <div class="text-center mt-3">
              <%= link_to "En savoir plus", entreprise_path, class: "btn btn-homepage homepage-btn"%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="wall-love">
  <hr>
  <div class="container">
    <div class="row">
      <h1 class="text-center mt-5 mb-5">MERCI</h1>
      <div class="col-lg-6 col-md-12 mb-3">
        <div class="card-product">
          <%= image_tag "img/rozenn.jpg", class: "avatar-home"%>
          <div class="card-product-infos">
            <h2>Rozenn </h2>
            <p>
              "Les cours avec Alexandre sont un condensé de techniques, de jeux et de bonne humeur. Il se met au niveau de chacun et avec beaucoup de patience et d'humour...<!--, il nous aide à progresser.-->"
            </p>
          </div>
        </div>
      </div>

      <div class="col-lg-6 col-md-12 mb-3">
        <div class="card-product">
          <%= image_tag "img/ilyes_avatar-bg.png", class: "avatar-home_1"%>
          <div class="card-product-infos">
            <h2>Ilyes</h2>
            <p>"J’ai eu la chance d’avoir comme coach le meilleur de tous, ses entraînements m’apportent beaucoup de joie, je me dépense tout en m’amusant..."
            </p>
          </div>
        </div>
      </div>

      <div class="col-lg-6 col-md-12 mb-3">
        <div class="card-product">
            <%= image_tag "img/maryse_avatar-bg.png", class: "avatar-home"%>
          <div class="card-product-infos">
            <h2>Maryse</h2>
            <p>
              "Les coachings de MAD m'ont beaucoup apporté. Son approche, son écoute, sa bienveillance, sa pédagogie et sa joie de vivre font de ses cours des moments de bonheur."
            </p>
          </div>
        </div>
      </div>

      <div class="col-lg-6 col-md-12 mb-3">
        <div class="card-product">
          <%= image_tag "img/Victor.jpg", class: "avatar-home"%>
          <div class="card-product-infos">
            <h2>Victor</h2>
            <p>"Agé de plus de 50 ans et pratiquant régulier depuis l’âge de 17 ans Alexandre a su me motiver et me challenger pour ne pas rester sur mes acquis...<!-- mais au contraire me pousser à remettre en cause ma pratique et renforcer mon cardio-->."
            </p>
          </div>
        </div>
      </div>
      <h6 class="text-center">
        <%= link_to "Voir plus de témoignages", merci_path, class: "link_merci" %>
      </h6>
    </div>
  </div>
</div>